"""Sugestões de nicho por categoria (o menu que aparece no campo de busca)
e a lista de UF + cidades principais."""
from __future__ import annotations

SUGESTOES = [
    ("Saúde", ["dentista", "clínica médica", "fisioterapia", "psicólogo",
               "nutricionista", "ótica", "dermatologista", "oftalmologista",
               "clínica veterinária", "laboratório de análises"]),
    ("Estética e bem-estar", ["clínica de estética", "salão de beleza", "barbearia",
                              "depilação a laser", "harmonização facial", "spa",
                              "manicure", "clínica de massagem"]),
    ("Fitness", ["academia", "crossfit", "pilates", "personal trainer",
                 "estúdio de yoga", "muay thai"]),
    ("Alimentação", ["pizzaria", "hamburgueria", "cafeteria", "confeitaria",
                     "restaurante japonês", "padaria", "açaí", "food truck",
                     "restaurante", "adega"]),
    ("Serviços profissionais", ["contabilidade", "advocacia", "arquitetura",
                                "engenharia civil", "consultoria empresarial",
                                "corretora de seguros", "imobiliária",
                                "despachante", "agência de viagens"]),
    ("Casa e reforma", ["marcenaria", "vidraçaria", "empresa de reformas",
                        "material de construção", "paisagismo", "dedetizadora",
                        "empresa de limpeza", "ar-condicionado"]),
    ("Automotivo", ["oficina mecânica", "funilaria e pintura", "estética automotiva",
                    "auto elétrica", "borracharia", "revenda de veículos"]),
    ("Educação", ["escola particular", "curso de idiomas", "curso preparatório",
                  "escola técnica", "autoescola", "escola de música"]),
    ("Eventos e varejo", ["buffet para eventos", "espaço para eventos", "floricultura",
                          "pet shop", "loja de roupas", "joalheria", "gráfica"]),
]

UFS = [
    ("AC", "Acre"), ("AL", "Alagoas"), ("AP", "Amapá"), ("AM", "Amazonas"),
    ("BA", "Bahia"), ("CE", "Ceará"), ("DF", "Distrito Federal"),
    ("ES", "Espírito Santo"), ("GO", "Goiás"), ("MA", "Maranhão"),
    ("MT", "Mato Grosso"), ("MS", "Mato Grosso do Sul"), ("MG", "Minas Gerais"),
    ("PA", "Pará"), ("PB", "Paraíba"), ("PR", "Paraná"), ("PE", "Pernambuco"),
    ("PI", "Piauí"), ("RJ", "Rio de Janeiro"), ("RN", "Rio Grande do Norte"),
    ("RS", "Rio Grande do Sul"), ("RO", "Rondônia"), ("RR", "Roraima"),
    ("SC", "Santa Catarina"), ("SP", "São Paulo"), ("SE", "Sergipe"),
    ("TO", "Tocantins"),
]

CIDADES = {
    "DF": ["Brasília", "Taguatinga", "Ceilândia", "Águas Claras", "Gama",
           "Sobradinho", "Planaltina", "Samambaia", "Guará", "Lago Sul",
           "Asa Norte", "Asa Sul", "Vicente Pires", "Recanto das Emas"],
    "SP": ["São Paulo", "Campinas", "Guarulhos", "São Bernardo do Campo",
           "Santo André", "Osasco", "Ribeirão Preto", "Sorocaba", "Santos",
           "São José dos Campos", "Bauru", "Piracicaba"],
    "RJ": ["Rio de Janeiro", "Niterói", "Duque de Caxias", "Nova Iguaçu",
           "São Gonçalo", "Campos dos Goytacazes", "Petrópolis", "Volta Redonda"],
    "MG": ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora",
           "Betim", "Montes Claros", "Uberaba"],
    "RS": ["Porto Alegre", "Caxias do Sul", "Canoas", "Pelotas",
           "Santa Maria", "Gravataí", "Novo Hamburgo", "São Leopoldo"],
    "PR": ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel", "Foz do Iguaçu"],
    "SC": ["Florianópolis", "Joinville", "Blumenau", "Chapecó", "Criciúma", "Itajaí"],
    "BA": ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Ilhéus"],
    "PE": ["Recife", "Jaboatão dos Guararapes", "Olinda", "Caruaru", "Petrolina"],
    "CE": ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Sobral"],
    "GO": ["Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde", "Luziânia"],
    "ES": ["Vitória", "Vila Velha", "Serra", "Cariacica"],
    "PA": ["Belém", "Ananindeua", "Santarém", "Marabá"],
    "AM": ["Manaus", "Parintins"],
    "MT": ["Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop"],
    "MS": ["Campo Grande", "Dourados", "Três Lagoas"],
    "RN": ["Natal", "Mossoró", "Parnamirim"],
    "PB": ["João Pessoa", "Campina Grande"],
    "AL": ["Maceió", "Arapiraca"],
    "SE": ["Aracaju", "Nossa Senhora do Socorro"],
    "PI": ["Teresina", "Parnaíba"],
    "MA": ["São Luís", "Imperatriz"],
    "TO": ["Palmas", "Araguaína"],
    "RO": ["Porto Velho", "Ji-Paraná"],
    "AC": ["Rio Branco"],
    "AP": ["Macapá"],
    "RR": ["Boa Vista"],
}
